kind: PersistentVolume
apiVersion: v1
metadata:
  name: volume-jenkins
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/ic/jenkins"
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: volume-jenkins
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi 