kind: PersistentVolume
apiVersion: v1
metadata:
  name: volume-mysql
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/ic/mysql"
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: volume-mysql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 